import type { LibraryEntry } from "../types.js";

/**
 * Community registry — 25 example entries showing the schema.
 * The full production registry (230+ libraries) is maintained privately
 * and compiled into the published npm package.
 *
 * To add a library, open a PR with the entry below.
 * Required: id, name, docsUrl. Optional but recommended: llmsTxtUrl, aliases, bestPracticesPaths.
 */
export const LIBRARY_REGISTRY: LibraryEntry[] = [
  // ─── JavaScript / TypeScript Frameworks ──────────────────────────────────────
  {
    id: "vercel/next.js",
    name: "Next.js",
    aliases: ["nextjs", "next", "next.js"],
    description: "The React Framework for the Web",
    docsUrl: "https://nextjs.org/docs",
    llmsTxtUrl: "https://nextjs.org/llms.txt",
    githubUrl: "https://github.com/vercel/next.js",
    npmPackage: "next",
    language: ["typescript", "javascript"],
    tags: ["framework", "react", "ssr", "fullstack"],
    bestPracticesPaths: [
      "/docs/app/building-your-application/rendering",
      "/docs/app/building-your-application/caching",
    ],
    urlPatterns: [
      "/docs/app/{slug}",
      "/docs/app/building-your-application/{slug}",
      "/docs/app/api-reference/{slug}",
    ],
  },
  {
    id: "facebook/react",
    name: "React",
    aliases: ["react", "reactjs"],
    description: "A JavaScript library for building user interfaces",
    docsUrl: "https://react.dev",
    llmsTxtUrl: "https://react.dev/llms.txt",
    githubUrl: "https://github.com/facebook/react",
    npmPackage: "react",
    language: ["typescript", "javascript"],
    tags: ["ui", "frontend", "library"],
    bestPracticesPaths: [
      "/learn/thinking-in-react",
      "/learn/managing-state",
      "/learn/escape-hatches",
      "/learn/you-might-not-need-an-effect",
      "/reference/rules",
      "/reference/react/hooks",
    ],
    urlPatterns: ["/reference/react/{slug}", "/learn/{slug}"],
  },
  {
    id: "vuejs/vue",
    name: "Vue.js",
    aliases: ["vue", "vuejs", "vue3"],
    description: "The Progressive JavaScript Framework",
    docsUrl: "https://vuejs.org/guide/introduction",
    llmsTxtUrl: "https://vuejs.org/llms.txt",
    githubUrl: "https://github.com/vuejs/core",
    npmPackage: "vue",
    language: ["typescript", "javascript"],
    tags: ["framework", "frontend"],
    bestPracticesPaths: [
      "/guide/best-practices/performance",
      "/guide/best-practices/security",
      "/guide/best-practices/accessibility",
      "/guide/best-practices/production-deployment",
      "/guide/scaling-up/state-management",
    ],
    urlPatterns: ["/guide/{slug}", "/api/{slug}"],
  },
  {
    id: "sveltejs/svelte",
    name: "Svelte",
    aliases: ["svelte"],
    description: "Cybernetically enhanced web apps",
    docsUrl: "https://svelte.dev/docs",
    llmsTxtUrl: "https://svelte.dev/llms.txt",
    llmsFullTxtUrl: "https://svelte.dev/llms-full.txt",
    githubUrl: "https://github.com/sveltejs/svelte",
    npmPackage: "svelte",
    language: ["typescript", "javascript"],
    tags: ["framework", "frontend", "compiler"],
    bestPracticesPaths: [
      "/docs/svelte/best-practices",
      "/docs/kit/performance",
      "/docs/svelte/reactivity",
      "/docs/kit/form-actions",
    ],
    urlPatterns: ["/docs/svelte/{slug}", "/docs/kit/{slug}"],
  },
  {
    id: "honojs/hono",
    name: "Hono",
    aliases: ["hono"],
    description: "Fast, lightweight web framework for the Edge",
    docsUrl: "https://hono.dev/docs",
    llmsTxtUrl: "https://hono.dev/llms.txt",
    llmsFullTxtUrl: "https://hono.dev/llms-full.txt",
    githubUrl: "https://github.com/honojs/hono",
    npmPackage: "hono",
    language: ["typescript", "javascript"],
    tags: ["framework", "edge", "backend", "api"],
    bestPracticesPaths: [
      "/docs/guides/best-practices",
      "/docs/guides/middleware",
      "/docs/guides/testing",
      "/docs/guides/validation",
    ],
    urlPatterns: ["/docs/{slug}", "/docs/guides/{slug}", "/docs/api/{slug}"],
  },
  {
    id: "expressjs/express",
    name: "Express",
    aliases: ["express", "expressjs"],
    description: "Fast, unopinionated, minimalist web framework for Node.js",
    docsUrl: "https://expressjs.com/en/4x/api.html",
    githubUrl: "https://github.com/expressjs/express",
    npmPackage: "express",
    language: ["typescript", "javascript"],
    tags: ["framework", "backend", "nodejs"],
    bestPracticesPaths: [
      "/en/advanced/best-practice-performance",
      "/en/advanced/best-practice-security",
      "/en/guide/error-handling",
      "/en/guide/routing",
    ],
    urlPatterns: ["/en/guide/{slug}", "/en/advanced/{slug}", "/en/4x/{slug}"],
  },

  // ─── CSS / Styling ────────────────────────────────────────────────────────────
  {
    id: "tailwindlabs/tailwindcss",
    name: "Tailwind CSS",
    aliases: ["tailwind", "tailwindcss"],
    description: "A utility-first CSS framework",
    docsUrl: "https://tailwindcss.com/docs",
    githubUrl: "https://github.com/tailwindlabs/tailwindcss",
    npmPackage: "tailwindcss",
    language: ["css"],
    tags: ["styling", "css", "utility-first"],
    bestPracticesPaths: [
      "/docs/utility-first",
      "/docs/reusing-styles",
      "/docs/adding-custom-styles",
      "/docs/optimizing-for-production",
      "/docs/responsive-design",
    ],
    urlPatterns: ["/docs/{slug}"],
  },
  {
    id: "shadcn/ui",
    name: "shadcn/ui",
    aliases: ["shadcn", "shadcn-ui"],
    description: "Accessible component library built on Radix UI and Tailwind CSS",
    docsUrl: "https://ui.shadcn.com/docs",
    llmsTxtUrl: "https://ui.shadcn.com/llms.txt",
    githubUrl: "https://github.com/shadcn-ui/ui",
    npmPackage: "@radix-ui/react-primitive",
    language: ["typescript"],
    tags: ["ui", "components", "accessible", "radix"],
    bestPracticesPaths: [
      "/docs/installation",
      "/docs/theming",
      "/docs/dark-mode",
      "/docs/components",
      "/docs/figma",
    ],
    urlPatterns: ["/docs/{slug}", "/docs/components/{slug}"],
  },

  // ─── Database / ORM ───────────────────────────────────────────────────────────
  {
    id: "drizzle-team/drizzle-orm",
    name: "Drizzle ORM",
    aliases: ["drizzle", "drizzle-orm"],
    description: "TypeScript ORM that is production ready",
    docsUrl: "https://orm.drizzle.team/docs/overview",
    llmsTxtUrl: "https://orm.drizzle.team/llms.txt",
    githubUrl: "https://github.com/drizzle-team/drizzle-orm",
    npmPackage: "drizzle-orm",
    language: ["typescript"],
    tags: ["orm", "database", "sql"],
    bestPracticesPaths: [
      "/docs/migrations",
      "/docs/rls",
      "/docs/guides",
      "/docs/performance",
      "/docs/joins",
      "/docs/transactions",
    ],
    urlPatterns: ["/docs/{slug}", "/docs/guides/{slug}"],
  },
  {
    id: "prisma/prisma",
    name: "Prisma",
    aliases: ["prisma"],
    description: "Next-generation Node.js and TypeScript ORM",
    docsUrl: "https://www.prisma.io/docs",
    llmsTxtUrl: "https://www.prisma.io/docs/llms.txt",
    githubUrl: "https://github.com/prisma/prisma",
    npmPackage: "prisma",
    language: ["typescript"],
    tags: ["orm", "database"],
    bestPracticesPaths: [
      "/docs/guides/performance-and-optimization",
      "/docs/guides/database/best-practices",
      "/docs/guides/testing",
      "/docs/concepts/components/prisma-client",
      "/docs/guides/migrate",
    ],
    urlPatterns: ["/docs/{slug}", "/docs/guides/{slug}", "/docs/concepts/{slug}"],
  },
  {
    id: "supabase/supabase",
    name: "Supabase",
    aliases: ["supabase"],
    description: "The open source Firebase alternative",
    docsUrl: "https://supabase.com/docs",
    llmsTxtUrl: "https://supabase.com/llms/js.txt",
    llmsFullTxtUrl: "https://supabase.com/llms/guides.txt",
    githubUrl: "https://github.com/supabase/supabase",
    npmPackage: "@supabase/supabase-js",
    language: ["typescript"],
    tags: ["backend", "database", "auth", "realtime", "storage", "edge-functions"],
    bestPracticesPaths: [
      "/docs/guides/auth/server-side/nextjs",
      "/docs/guides/database/postgres/row-level-security",
      "/docs/guides/realtime",
      "/docs/guides/realtime/presence",
      "/docs/guides/storage",
      "/docs/guides/functions",
    ],
    urlPatterns: ["/docs/guides/{slug}", "/docs/reference/javascript/{slug}"],
  },

  // ─── Validation / Schema ──────────────────────────────────────────────────────
  {
    id: "colinhacks/zod",
    name: "Zod",
    aliases: ["zod"],
    description: "TypeScript-first schema validation with static type inference",
    docsUrl: "https://zod.dev",
    llmsTxtUrl: "https://zod.dev/llms.txt",
    githubUrl: "https://github.com/colinhacks/zod",
    npmPackage: "zod",
    language: ["typescript"],
    tags: ["validation", "schema", "types"],
    bestPracticesPaths: [
      "/basics",
      "/parsing",
      "/error-handling",
      "/transforms",
    ],
    urlPatterns: ["/{slug}"],
  },

  // ─── State Management ─────────────────────────────────────────────────────────
  {
    id: "pmndrs/zustand",
    name: "Zustand",
    aliases: ["zustand"],
    description: "A small, fast and scalable state-management solution",
    docsUrl: "https://zustand.docs.pmnd.rs",
    llmsTxtUrl: "https://zustand.docs.pmnd.rs/llms.txt",
    githubUrl: "https://github.com/pmndrs/zustand",
    npmPackage: "zustand",
    language: ["typescript", "javascript"],
    tags: ["state", "react"],
    bestPracticesPaths: [
      "/guides/updating-state",
      "/guides/typescript",
      "/guides/testing",
      "/guides/practice/no-unnecessary-computations",
    ],
    urlPatterns: ["/guides/{slug}"],
  },
  {
    id: "TanStack/query",
    name: "TanStack Query",
    aliases: ["tanstack-query", "react-query", "tanstack query"],
    description: "Asynchronous state management for TS/JS, React, Solid, Vue and Svelte",
    docsUrl: "https://tanstack.com/query/latest/docs/framework/react/overview",
    llmsTxtUrl: "https://tanstack.com/llms.txt",
    githubUrl: "https://github.com/TanStack/query",
    npmPackage: "@tanstack/react-query",
    language: ["typescript"],
    tags: ["state", "async", "fetching", "react"],
    bestPracticesPaths: [
      "/query/latest/docs/framework/react/guides/important-defaults",
      "/query/latest/docs/framework/react/guides/caching",
      "/query/latest/docs/framework/react/guides/optimistic-updates",
      "/query/latest/docs/framework/react/guides/testing",
      "/query/latest/docs/framework/react/guides/ssr",
    ],
    urlPatterns: ["/query/latest/docs/framework/react/{slug}", "/query/latest/docs/framework/react/guides/{slug}"],
  },

  // ─── Testing ──────────────────────────────────────────────────────────────────
  {
    id: "vitest-dev/vitest",
    name: "Vitest",
    aliases: ["vitest"],
    description: "Blazing Fast Vite-native Test Framework",
    docsUrl: "https://vitest.dev/api",
    llmsTxtUrl: "https://vitest.dev/llms.txt",
    githubUrl: "https://github.com/vitest-dev/vitest",
    npmPackage: "vitest",
    language: ["typescript", "javascript"],
    tags: ["testing", "unit"],
    bestPracticesPaths: [
      "/guide/",
      "/guide/mocking",
      "/guide/snapshot",
      "/guide/coverage",
      "/guide/testing-types",
    ],
    urlPatterns: ["/guide/{slug}", "/api/{slug}", "/config/{slug}"],
  },
  {
    id: "microsoft/playwright",
    name: "Playwright",
    aliases: ["playwright"],
    description: "Fast and reliable end-to-end testing for modern web apps",
    docsUrl: "https://playwright.dev/docs/api/class-playwright",
    githubUrl: "https://github.com/microsoft/playwright",
    npmPackage: "@playwright/test",
    language: ["typescript", "javascript"],
    tags: ["testing", "e2e", "browser"],
    bestPracticesPaths: [
      "/docs/best-practices",
      "/docs/test-assertions",
      "/docs/locators",
      "/docs/auth",
      "/docs/test-configuration",
    ],
    urlPatterns: ["/docs/{slug}", "/docs/api/class-{slug}"],
  },

  // ─── Build Tools ──────────────────────────────────────────────────────────────
  {
    id: "vitejs/vite",
    name: "Vite",
    aliases: ["vite"],
    description: "Next generation frontend tooling",
    docsUrl: "https://vite.dev/guide",
    llmsTxtUrl: "https://vite.dev/llms.txt",
    githubUrl: "https://github.com/vitejs/vite",
    npmPackage: "vite",
    language: ["typescript", "javascript"],
    tags: ["build", "bundler", "dev-server"],
    bestPracticesPaths: [
      "/guide/features",
      "/guide/performance",
      "/guide/build",
      "/guide/ssr",
      "/guide/env-and-mode",
    ],
    urlPatterns: ["/guide/{slug}", "/config/{slug}"],
  },

  // ─── AI / ML ──────────────────────────────────────────────────────────────────
  {
    id: "vercel/ai",
    name: "Vercel AI SDK",
    aliases: ["ai-sdk", "vercel ai", "ai sdk"],
    description: "TypeScript toolkit for building AI-powered applications",
    docsUrl: "https://ai-sdk.dev/docs",
    llmsTxtUrl: "https://ai-sdk.dev/llms.txt",
    githubUrl: "https://github.com/vercel/ai",
    npmPackage: "ai",
    language: ["typescript"],
    tags: ["ai", "llm", "streaming"],
    bestPracticesPaths: [
      "/docs/ai-sdk-core/overview",
      "/docs/ai-sdk-ui/overview",
      "/docs/ai-sdk-core/agents",
      "/docs/ai-sdk-core/tools-and-tool-calling",
      "/docs/ai-sdk-core/generating-structured-data",
      "/docs/ai-sdk-core/streaming",
    ],
    urlPatterns: ["/docs/{slug}", "/docs/ai-sdk-core/{slug}", "/docs/ai-sdk-ui/{slug}"],
  },

  // ─── Mobile / React Native ────────────────────────────────────────────────────
  {
    id: "expo/expo",
    name: "Expo",
    aliases: ["expo"],
    description: "An open-source platform for making universal native apps",
    docsUrl: "https://docs.expo.dev",
    llmsTxtUrl: "https://docs.expo.dev/llms.txt",
    githubUrl: "https://github.com/expo/expo",
    npmPackage: "expo",
    language: ["typescript", "javascript"],
    tags: ["mobile", "react-native", "cross-platform"],
    bestPracticesPaths: [
      "/develop/development-builds/introduction",
      "/guides/file-based-routing",
      "/router/introduction",
      "/eas",
      "/deploy/submit-to-app-stores",
    ],
    urlPatterns: ["/docs/{slug}", "/router/{slug}", "/versions/latest/sdk/{slug}"],
  },
  {
    id: "facebook/react-native",
    name: "React Native",
    aliases: ["react-native", "rn", "reactnative"],
    description: "A framework for building native apps using React",
    docsUrl: "https://reactnative.dev/docs/getting-started",
    llmsTxtUrl: "https://reactnative.dev/llms.txt",
    githubUrl: "https://github.com/facebook/react-native",
    npmPackage: "react-native",
    language: ["typescript", "javascript"],
    tags: ["mobile", "cross-platform", "native"],
    bestPracticesPaths: [
      "/docs/performance",
      "/docs/style",
      "/docs/testing-overview",
      "/architecture/overview",
      "/docs/security",
    ],
    urlPatterns: ["/docs/{slug}", "/docs/components/{slug}"],
  },

  // ─── Python ───────────────────────────────────────────────────────────────────
  {
    id: "tiangolo/fastapi",
    name: "FastAPI",
    aliases: ["fastapi"],
    description: "FastAPI framework, high performance, easy to learn",
    docsUrl: "https://fastapi.tiangolo.com",
    githubUrl: "https://github.com/tiangolo/fastapi",
    pypiPackage: "fastapi",
    language: ["python"],
    tags: ["framework", "backend", "api", "async"],
    bestPracticesPaths: [
      "/tutorial/",
      "/advanced/",
      "/deployment/",
      "/async/",
      "/tutorial/security/",
    ],
    urlPatterns: ["/tutorial/{slug}", "/advanced/{slug}"],
  },
  {
    id: "django/django",
    name: "Django",
    aliases: ["django"],
    description: "The web framework for perfectionists with deadlines",
    docsUrl: "https://docs.djangoproject.com/en/stable",
    githubUrl: "https://github.com/django/django",
    pypiPackage: "django",
    language: ["python"],
    tags: ["framework", "backend", "fullstack"],
    bestPracticesPaths: [
      "/en/stable/topics/security/",
      "/en/stable/topics/performance/",
      "/en/stable/topics/testing/",
      "/en/stable/misc/design-philosophies/",
      "/en/stable/howto/deployment/",
    ],
    urlPatterns: ["/en/stable/topics/{slug}", "/en/stable/ref/{slug}", "/en/stable/howto/{slug}"],
  },

  // ─── Infrastructure ───────────────────────────────────────────────────────────
  {
    id: "astro-build/astro",
    name: "Astro",
    aliases: ["astro"],
    description: "The web framework for content-driven websites",
    docsUrl: "https://docs.astro.build",
    llmsTxtUrl: "https://docs.astro.build/llms.txt",
    llmsFullTxtUrl: "https://docs.astro.build/llms-full.txt",
    githubUrl: "https://github.com/withastro/astro",
    npmPackage: "astro",
    language: ["typescript", "javascript"],
    tags: ["framework", "ssg", "content"],
    bestPracticesPaths: [
      "/en/guides/best-practices/",
      "/en/guides/performance/",
      "/en/guides/deploy/",
      "/en/guides/server-side-rendering/",
      "/en/guides/content-collections/",
    ],
    urlPatterns: ["/en/guides/{slug}", "/en/reference/{slug}"],
  },
  {
    id: "withastro/starlight",
    name: "Starlight",
    aliases: ["starlight"],
    description: "Build documentation sites with Astro",
    docsUrl: "https://starlight.astro.build/getting-started",
    githubUrl: "https://github.com/withastro/starlight",
    npmPackage: "@astrojs/starlight",
    language: ["typescript"],
    tags: ["docs", "astro", "static"],
    bestPracticesPaths: [
      "/getting-started/",
      "/guides/customization/",
      "/guides/i18n/",
      "/guides/sidebar/",
    ],
    urlPatterns: ["/guides/{slug}", "/reference/{slug}"],
  },

  // ─── AI / LLM SDKs ────────────────────────────────────────────────────────────
  {
    id: "anthropics/anthropic-sdk-node",
    name: "Anthropic SDK",
    aliases: ["anthropic", "@anthropic-ai/sdk", "anthropic-sdk"],
    description: "Official TypeScript SDK for the Anthropic Claude API",
    docsUrl: "https://docs.anthropic.com",
    llmsTxtUrl: "https://platform.claude.com/llms.txt",
    githubUrl: "https://github.com/anthropics/anthropic-sdk-node",
    npmPackage: "@anthropic-ai/sdk",
    language: ["typescript", "javascript"],
    tags: ["ai", "llm", "sdk"],
    bestPracticesPaths: [
      "/en/docs/build-with-claude/overview",
      "/en/docs/build-with-claude/tool-use",
      "/en/docs/build-with-claude/prompt-engineering/overview",
      "/en/docs/build-with-claude/streaming",
      "/en/docs/build-with-claude/prompt-caching",
    ],
    urlPatterns: ["/en/docs/{slug}", "/en/docs/build-with-claude/{slug}", "/en/api/{slug}"],
  },
  {
    id: "anthropics/claude-code",
    name: "Claude Code",
    aliases: [
      "claude-code",
      "claude code",
      "claudecode",
      "@anthropic-ai/claude-code",
    ],
    description:
      "Agentic coding tool and Agent SDK by Anthropic — CLI, IDE, desktop, web, GitHub Actions, and programmatic SDK",
    docsUrl: "https://code.claude.com/docs/en/overview",
    llmsTxtUrl: "https://code.claude.com/docs/llms.txt",
    githubUrl: "https://github.com/anthropics/claude-code",
    npmPackage: "@anthropic-ai/claude-code",
    language: ["typescript", "javascript", "python"],
    tags: ["ai", "cli", "agent", "coding", "sdk", "mcp", "ide"],
    bestPracticesPaths: [
      // ── Getting started ──
      "/en/overview",
      "/en/quickstart",
      "/en/how-claude-code-works",
      "/en/best-practices",
      "/en/common-workflows",
      "/en/features-overview",
      // ── Memory & configuration ──
      "/en/memory",
      "/en/settings",
      "/en/permissions",
      "/en/model-config",
      "/en/env-vars",
      "/en/fast-mode",
      "/en/keybindings",
      "/en/statusline",
      "/en/terminal-config",
      "/en/output-styles",
      "/en/sandboxing",
      // ── Extensibility ──
      "/en/skills",
      "/en/sub-agents",
      "/en/agent-teams",
      "/en/hooks-guide",
      "/en/hooks",
      "/en/mcp",
      "/en/plugins",
      "/en/plugins-reference",
      "/en/discover-plugins",
      "/en/plugin-marketplaces",
      "/en/channels",
      "/en/channels-reference",
      "/en/scheduled-tasks",
      "/en/headless",
      // ── Platforms & integrations ──
      "/en/vs-code",
      "/en/jetbrains",
      "/en/desktop",
      "/en/desktop-quickstart",
      "/en/claude-code-on-the-web",
      "/en/remote-control",
      "/en/chrome",
      "/en/slack",
      "/en/github-actions",
      "/en/gitlab-ci-cd",
      "/en/code-review",
      "/en/voice-dictation",
      // ── Reference ──
      "/en/cli-reference",
      "/en/commands",
      "/en/tools-reference",
      "/en/interactive-mode",
      "/en/checkpointing",
      // ── Deployment & enterprise ──
      "/en/third-party-integrations",
      "/en/amazon-bedrock",
      "/en/google-vertex-ai",
      "/en/microsoft-foundry",
      "/en/network-config",
      "/en/llm-gateway",
      "/en/devcontainer",
      "/en/server-managed-settings",
      "/en/authentication",
      // ── Administration ──
      "/en/setup",
      "/en/security",
      "/en/data-usage",
      "/en/zero-data-retention",
      "/en/monitoring-usage",
      "/en/costs",
      "/en/analytics",
      "/en/troubleshooting",
      "/en/legal-and-compliance",
      "/en/changelog",
    ],
    urlPatterns: ["/en/{slug}"],
  },
  {
    id: "anthropics/claude-agent-sdk",
    name: "Claude Agent SDK",
    aliases: [
      "claude-agent-sdk",
      "claude agent sdk",
      "claude-code-sdk",
      "claude code sdk",
      "agent-sdk",
      "@anthropic-ai/claude-agent-sdk",
    ],
    description:
      "Build AI agents powered by the same tools and agent loop as Claude Code — Python and TypeScript",
    docsUrl: "https://platform.claude.com/docs/en/agent-sdk/overview",
    llmsTxtUrl: "https://platform.claude.com/llms.txt",
    githubUrl: "https://github.com/anthropics/claude-code",
    npmPackage: "@anthropic-ai/claude-code",
    language: ["typescript", "javascript", "python"],
    tags: ["ai", "agent", "sdk", "automation"],
    bestPracticesPaths: [
      "/en/agent-sdk/overview",
      "/en/agent-sdk/quickstart",
      "/en/agent-sdk/agent-loop",
      "/en/agent-sdk/python",
      "/en/agent-sdk/typescript",
      "/en/agent-sdk/typescript-v2-preview",
      "/en/agent-sdk/permissions",
      "/en/agent-sdk/custom-tools",
      "/en/agent-sdk/subagents",
      "/en/agent-sdk/skills",
      "/en/agent-sdk/mcp",
      "/en/agent-sdk/plugins",
      "/en/agent-sdk/hosting",
      "/en/agent-sdk/cost-tracking",
      "/en/agent-sdk/todo-tracking",
      "/en/agent-sdk/structured-outputs",
      "/en/agent-sdk/secure-deployment",
      "/en/agent-sdk/claude-code-features",
      "/en/agent-sdk/migration-guide",
    ],
    urlPatterns: ["/en/agent-sdk/{slug}"],
  },
  {
    id: "openai/openai-node",
    name: "OpenAI SDK",
    aliases: ["openai", "openai-sdk"],
    description: "Official TypeScript/JavaScript SDK for the OpenAI API",
    docsUrl: "https://platform.openai.com/docs",
    githubUrl: "https://github.com/openai/openai-node",
    npmPackage: "openai",
    language: ["typescript", "javascript"],
    tags: ["ai", "llm", "sdk"],
    bestPracticesPaths: [
      "/docs/guides/text-generation",
      "/docs/guides/function-calling",
      "/docs/guides/structured-outputs",
      "/docs/guides/prompt-engineering",
      "/docs/guides/production-best-practices",
    ],
    urlPatterns: ["/docs/{slug}", "/docs/guides/{slug}", "/docs/api-reference/{slug}"],
  },
  {
    id: "modelcontextprotocol/sdk",
    name: "MCP SDK",
    aliases: ["mcp", "mcp-sdk", "@modelcontextprotocol/sdk", "model-context-protocol"],
    description: "TypeScript SDK for the Model Context Protocol",
    docsUrl: "https://modelcontextprotocol.io/docs",
    llmsTxtUrl: "https://modelcontextprotocol.io/llms.txt",
    githubUrl: "https://github.com/modelcontextprotocol/typescript-sdk",
    npmPackage: "@modelcontextprotocol/sdk",
    language: ["typescript"],
    tags: ["ai", "mcp", "sdk"],
    bestPracticesPaths: [
      "/docs/concepts/architecture",
      "/docs/concepts/tools",
      "/docs/concepts/resources",
      "/docs/concepts/prompts",
      "/docs/concepts/transports",
    ],
    urlPatterns: ["/docs/{slug}", "/docs/concepts/{slug}"],
  },

  // ─── Frameworks ────────────────────────────────────────────────────────────────
  {
    id: "remix-run/remix",
    name: "Remix",
    aliases: ["remix", "@remix-run/react"],
    description: "Full stack web framework focused on web standards and user experience",
    docsUrl: "https://remix.run/docs",
    githubUrl: "https://github.com/remix-run/remix",
    npmPackage: "@remix-run/react",
    language: ["typescript", "javascript"],
    tags: ["framework", "fullstack", "react"],
    bestPracticesPaths: [
      "/docs/guides/data-loading",
      "/docs/guides/form-validation",
      "/docs/guides/styling",
      "/docs/guides/deployment",
    ],
    urlPatterns: ["/docs/{slug}", "/docs/guides/{slug}", "/docs/api/{slug}"],
  },
  {
    id: "nuxt/nuxt",
    name: "Nuxt",
    aliases: ["nuxt", "nuxt3", "nuxt.js"],
    description: "The intuitive Vue framework for building universal web applications",
    docsUrl: "https://nuxt.com/docs",
    llmsTxtUrl: "https://nuxt.com/llms.txt",
    llmsFullTxtUrl: "https://nuxt.com/llms-full.txt",
    githubUrl: "https://github.com/nuxt/nuxt",
    npmPackage: "nuxt",
    language: ["typescript", "javascript"],
    tags: ["framework", "vue", "fullstack"],
    bestPracticesPaths: [
      "/docs/guide/concepts/rendering",
      "/docs/guide/best-practices/performance",
      "/docs/guide/directory-structure",
      "/docs/guide/going-further/experimental-features",
    ],
    urlPatterns: ["/docs/guide/{slug}", "/docs/api/{slug}"],
  },
  {
    id: "sveltejs/kit",
    name: "SvelteKit",
    aliases: ["sveltekit", "@sveltejs/kit"],
    description: "Web application framework powered by Svelte",
    docsUrl: "https://svelte.dev/docs/kit",
    llmsTxtUrl: "https://svelte.dev/llms.txt",
    githubUrl: "https://github.com/sveltejs/kit",
    npmPackage: "@sveltejs/kit",
    language: ["typescript", "javascript"],
    tags: ["framework", "svelte", "fullstack"],
    bestPracticesPaths: [
      "/docs/kit/performance",
      "/docs/kit/form-actions",
      "/docs/kit/hooks",
      "/docs/kit/routing",
    ],
    urlPatterns: ["/docs/kit/{slug}", "/docs/svelte/{slug}"],
  },
  {
    id: "solidjs/solid",
    name: "SolidJS",
    aliases: ["solid", "solid-js", "solidjs"],
    description: "A declarative JavaScript library for building user interfaces",
    docsUrl: "https://docs.solidjs.com",
    llmsTxtUrl: "https://docs.solidjs.com/llms.txt",
    githubUrl: "https://github.com/solidjs/solid",
    npmPackage: "solid-js",
    language: ["typescript", "javascript"],
    tags: ["framework", "ui", "reactive"],
    bestPracticesPaths: [
      "/concepts/signals",
      "/guides/state-management",
      "/guides/routing",
      "/guides/fetching-data",
    ],
    urlPatterns: ["/concepts/{slug}", "/guides/{slug}", "/reference/{slug}"],
  },
  {
    id: "fastify/fastify",
    name: "Fastify",
    aliases: ["fastify"],
    description: "Fast and low overhead web framework for Node.js",
    docsUrl: "https://fastify.dev/docs/latest",
    llmsTxtUrl: "https://fastify.dev/llms.txt",
    githubUrl: "https://github.com/fastify/fastify",
    npmPackage: "fastify",
    language: ["typescript", "javascript"],
    tags: ["framework", "backend", "http"],
    bestPracticesPaths: [
      "/docs/latest/Guides/Getting-Started",
      "/docs/latest/Guides/Testing",
      "/docs/latest/Guides/Plugins-Guide",
      "/docs/latest/Guides/Recommendations",
    ],
    urlPatterns: ["/docs/latest/{slug}", "/docs/latest/Guides/{slug}", "/docs/latest/Reference/{slug}"],
  },
  {
    id: "trpc/trpc",
    name: "tRPC",
    aliases: ["trpc", "@trpc/server", "@trpc/client"],
    description: "End-to-end typesafe APIs made easy",
    docsUrl: "https://trpc.io/docs",
    llmsTxtUrl: "https://trpc.io/llms.txt",
    githubUrl: "https://github.com/trpc/trpc",
    npmPackage: "@trpc/server",
    language: ["typescript"],
    tags: ["api", "rpc", "typesafe"],
    bestPracticesPaths: [
      "/docs/server/procedures",
      "/docs/client/nextjs",
      "/docs/server/middlewares",
      "/docs/server/error-handling",
    ],
    urlPatterns: ["/docs/{slug}", "/docs/server/{slug}", "/docs/client/{slug}"],
  },

  // ─── State / Validation ────────────────────────────────────────────────────────
  {
    id: "pmndrs/jotai",
    name: "Jotai",
    aliases: ["jotai"],
    description: "Primitive and flexible state management for React",
    docsUrl: "https://jotai.org/docs/introduction",
    githubUrl: "https://github.com/pmndrs/jotai",
    npmPackage: "jotai",
    language: ["typescript", "javascript"],
    tags: ["state", "react", "atoms"],
    bestPracticesPaths: [
      "/docs/guides/typescript",
      "/docs/guides/testing",
      "/docs/guides/performance",
      "/docs/guides/composing-atoms",
    ],
    urlPatterns: ["/docs/{slug}", "/docs/guides/{slug}", "/docs/utilities/{slug}"],
  },
  {
    id: "fabian-hiller/valibot",
    name: "Valibot",
    aliases: ["valibot"],
    description: "A modular and type safe schema library for validating structural data",
    docsUrl: "https://valibot.dev/guides/introduction",
    llmsTxtUrl: "https://valibot.dev/llms.txt",
    githubUrl: "https://github.com/fabian-hiller/valibot",
    npmPackage: "valibot",
    language: ["typescript"],
    tags: ["validation", "schema", "types"],
    bestPracticesPaths: [
      "/guides/introduction/",
      "/guides/migrate-from-zod/",
      "/guides/schemas/",
      "/guides/methods/",
    ],
    urlPatterns: ["/guides/{slug}", "/api/{slug}"],
  },
  {
    id: "Effect-TS/effect",
    name: "Effect",
    aliases: ["effect", "effect-ts"],
    description: "The missing standard library for TypeScript",
    docsUrl: "https://effect.website/docs",
    llmsTxtUrl: "https://effect.website/llms.txt",
    githubUrl: "https://github.com/Effect-TS/effect",
    npmPackage: "effect",
    language: ["typescript"],
    tags: ["functional", "effects", "typescript"],
    bestPracticesPaths: [
      "/docs/introduction",
      "/docs/error-management/expected-errors",
      "/docs/concurrency/basic-concurrency",
      "/docs/guides/configuration",
    ],
    urlPatterns: ["/docs/{slug}", "/docs/guides/{slug}"],
  },

  // ─── Auth ──────────────────────────────────────────────────────────────────────
  {
    id: "nextauthjs/next-auth",
    name: "Auth.js",
    aliases: ["auth.js", "authjs", "next-auth", "nextauth"],
    description: "Authentication for the Web — works with Next.js, SvelteKit, and more",
    docsUrl: "https://authjs.dev/getting-started",
    githubUrl: "https://github.com/nextauthjs/next-auth",
    npmPackage: "next-auth",
    language: ["typescript", "javascript"],
    tags: ["auth", "oauth", "sessions"],
    bestPracticesPaths: [
      "/getting-started",
      "/getting-started/providers",
      "/concepts/session-management",
      "/getting-started/deployment",
    ],
    urlPatterns: ["/getting-started/{slug}", "/concepts/{slug}", "/guides/{slug}"],
  },

  // ─── Database / Backend ────────────────────────────────────────────────────────
  {
    id: "socketio/socket.io",
    name: "Socket.IO",
    aliases: ["socket.io", "socketio", "socket-io"],
    description: "Bidirectional and low-latency communication for every platform",
    docsUrl: "https://socket.io/docs/v4",
    githubUrl: "https://github.com/socketio/socket.io",
    npmPackage: "socket.io",
    language: ["typescript", "javascript"],
    tags: ["realtime", "websockets", "networking"],
    bestPracticesPaths: [
      "/docs/v4/",
      "/docs/v4/performance-tuning/",
      "/docs/v4/rooms/",
      "/docs/v4/middlewares/",
    ],
    urlPatterns: ["/docs/v4/{slug}"],
  },
  {
    id: "mongoose/mongoose",
    name: "Mongoose",
    aliases: ["mongoose"],
    description: "MongoDB object modeling designed to work in an asynchronous environment",
    docsUrl: "https://mongoosejs.com/docs",
    githubUrl: "https://github.com/Automattic/mongoose",
    npmPackage: "mongoose",
    language: ["typescript", "javascript"],
    tags: ["database", "mongodb", "odm"],
    bestPracticesPaths: [
      "/docs/guide.html",
      "/docs/best_practices.html",
      "/docs/indexes.html",
      "/docs/middleware.html",
    ],
    urlPatterns: ["/docs/{slug}"],
  },

  // ─── Content / CMS ─────────────────────────────────────────────────────────────
  {
    id: "payloadcms/payload",
    name: "Payload CMS",
    aliases: ["payload", "payloadcms", "payload-cms"],
    description: "The most powerful TypeScript CMS — headless, code-first, Next.js native",
    docsUrl: "https://payloadcms.com/docs",
    llmsTxtUrl: "https://payloadcms.com/llms.txt",
    githubUrl: "https://github.com/payloadcms/payload",
    npmPackage: "payload",
    language: ["typescript"],
    tags: ["cms", "headless", "nextjs"],
    bestPracticesPaths: [
      "/docs/getting-started/what-is-payload",
      "/docs/configuration/overview",
      "/docs/access-control/overview",
      "/docs/fields/overview",
    ],
    urlPatterns: ["/docs/{slug}", "/docs/fields/{slug}", "/docs/admin/{slug}"],
  },

  // ─── Tooling / Runtime ─────────────────────────────────────────────────────────
  {
    id: "oven-sh/bun",
    name: "Bun",
    aliases: ["bun", "bun.sh"],
    description: "All-in-one JavaScript runtime and toolkit: bundler, test runner, package manager",
    docsUrl: "https://bun.sh/docs",
    llmsTxtUrl: "https://bun.sh/llms.txt",
    githubUrl: "https://github.com/oven-sh/bun",
    language: ["typescript", "javascript"],
    tags: ["runtime", "bundler", "tooling"],
    bestPracticesPaths: [
      "/docs",
      "/docs/runtime/modules",
      "/docs/bundler",
      "/docs/test/writing",
    ],
    urlPatterns: ["/docs/{slug}", "/guides/{slug}"],
  },
  {
    id: "denoland/deno",
    name: "Deno",
    aliases: ["deno"],
    description: "A modern runtime for JavaScript and TypeScript",
    docsUrl: "https://docs.deno.com",
    llmsTxtUrl: "https://docs.deno.com/llms.txt",
    githubUrl: "https://github.com/denoland/deno",
    language: ["typescript", "javascript"],
    tags: ["runtime", "deno", "secure"],
    bestPracticesPaths: [
      "/runtime/fundamentals/",
      "/runtime/contributing/style_guide/",
      "/runtime/fundamentals/security/",
      "/deploy/",
    ],
    urlPatterns: ["/runtime/{slug}", "/deploy/{slug}"],
  },
  {
    id: "storybookjs/storybook",
    name: "Storybook",
    aliases: ["storybook"],
    description: "Frontend workshop for building UI components and pages in isolation",
    docsUrl: "https://storybook.js.org/docs",
    githubUrl: "https://github.com/storybookjs/storybook",
    npmPackage: "storybook",
    language: ["typescript", "javascript"],
    tags: ["ui", "components", "testing"],
    bestPracticesPaths: [
      "/docs/get-started",
      "/docs/writing-stories",
      "/docs/writing-tests",
      "/docs/configure",
    ],
    urlPatterns: ["/docs/{slug}", "/docs/api/{slug}"],
  },

  // ─── Animation / Graphics ──────────────────────────────────────────────────────
  {
    id: "motiondivision/motion",
    name: "Motion",
    aliases: ["motion", "framer-motion", "motion-one"],
    description: "A production-ready motion library for React and JavaScript",
    docsUrl: "https://motion.dev/docs",
    githubUrl: "https://github.com/motiondivision/motion",
    npmPackage: "motion",
    language: ["typescript", "javascript"],
    tags: ["animation", "react", "ui"],
    bestPracticesPaths: [
      "/docs/",
      "/docs/animate",
      "/docs/gestures",
      "/docs/layout-animations",
    ],
    urlPatterns: ["/docs/{slug}"],
  },
  {
    id: "mrdoob/three.js",
    name: "Three.js",
    aliases: ["three", "three.js", "threejs"],
    description: "JavaScript 3D library — WebGL renderer for the web",
    docsUrl: "https://threejs.org/docs",
    githubUrl: "https://github.com/mrdoob/three.js",
    npmPackage: "three",
    language: ["typescript", "javascript"],
    tags: ["3d", "webgl", "graphics"],
    bestPracticesPaths: [
      "/docs/index.html#manual/en/introduction/Creating-a-scene",
      "/docs/index.html#manual/en/introduction/How-to-dispose-of-objects",
    ],
    urlPatterns: ["/docs/index.html#manual/en/{slug}", "/docs/index.html#api/en/{slug}"],
  },

  // ─── Google / Firebase / GCP ────────────────────────────────────────────────
  {
    id: "google/generative-ai-js",
    name: "Google Gemini API",
    aliases: ["gemini", "gemini-api", "@google/generative-ai", "google-ai", "google-generative-ai"],
    description: "Google Gemini API client for JavaScript and TypeScript",
    docsUrl: "https://ai.google.dev/gemini-api/docs",
    githubUrl: "https://github.com/google-gemini/generative-ai-js",
    npmPackage: "@google/generative-ai",
    language: ["typescript", "javascript"],
    tags: ["ai", "llm", "google", "gemini", "multimodal"],
    bestPracticesPaths: [
      "/gemini-api/docs/get-started/tutorial",
      "/gemini-api/docs/models/gemini",
      "/gemini-api/docs/api-key",
      "/gemini-api/docs/function-calling",
      "/gemini-api/docs/structured-output",
      "/gemini-api/docs/embeddings",
      "/gemini-api/docs/caching",
      "/gemini-api/docs/context-caching",
      "/gemini-api/docs/safety-settings",
      "/gemini-api/docs/thinking",
      "/gemini-api/docs/image-understanding",
      "/gemini-api/docs/audio",
      "/gemini-api/docs/video",
      "/gemini-api/docs/code-execution",
      "/gemini-api/docs/grounding",
      "/gemini-api/docs/live-api",
    ],
    urlPatterns: ["/gemini-api/docs/{slug}"],
  },
  {
    id: "google/generative-ai-python",
    name: "Google Gemini Python SDK",
    aliases: ["gemini-python", "google-genai", "google-generativeai-python"],
    description: "Google Gemini API client for Python",
    docsUrl: "https://ai.google.dev/gemini-api/docs",
    githubUrl: "https://github.com/google-gemini/generative-ai-python",
    pypiPackage: "google-generativeai",
    language: ["python"],
    tags: ["ai", "llm", "google", "gemini", "sdk"],
    bestPracticesPaths: [
      "/gemini-api/docs/get-started/tutorial",
      "/gemini-api/docs/function-calling",
      "/gemini-api/docs/structured-output",
      "/gemini-api/docs/embeddings",
    ],
    urlPatterns: ["/gemini-api/docs/{slug}"],
  },
  {
    id: "firebase/firebase-js-sdk",
    name: "Firebase",
    aliases: ["firebase", "firestore", "firebase-auth", "firebase-js"],
    description: "Firebase JavaScript SDK for web and Node.js apps",
    docsUrl: "https://firebase.google.com/docs",
    llmsTxtUrl: "https://firebase.google.com/docs/llms.txt",
    githubUrl: "https://github.com/firebase/firebase-js-sdk",
    npmPackage: "firebase",
    language: ["typescript", "javascript"],
    tags: ["backend", "database", "auth", "google", "realtime", "hosting"],
    bestPracticesPaths: [
      "/docs/firestore",
      "/docs/auth",
      "/docs/functions",
      "/docs/hosting",
      "/docs/storage",
      "/docs/database",
      "/docs/cloud-messaging",
      "/docs/remote-config",
      "/docs/app-check",
    ],
    urlPatterns: ["/docs/{slug}"],
  },
  {
    id: "googleapis/google-cloud-node",
    name: "Google Cloud",
    aliases: ["gcp", "google-cloud", "@google-cloud", "google-cloud-platform"],
    description: "Google Cloud client libraries for Node.js",
    docsUrl: "https://cloud.google.com/nodejs/docs/reference",
    githubUrl: "https://github.com/googleapis/google-cloud-node",
    npmPackage: "@google-cloud/storage",
    language: ["typescript", "javascript"],
    tags: ["cloud", "google", "infrastructure", "storage", "compute"],
    bestPracticesPaths: [
      "/storage/docs",
      "/bigquery/docs",
      "/run/docs",
      "/functions/docs",
      "/pubsub/docs",
      "/kubernetes-engine/docs",
      "/iam/docs",
      "/logging/docs",
    ],
    urlPatterns: ["/{slug}/docs"],
  },
  {
    id: "googleapis/google-api-nodejs-client",
    name: "Google APIs Client",
    aliases: ["googleapis", "google-apis", "google-api-client"],
    description: "Google APIs client library for Node.js — Sheets, Drive, Calendar, YouTube, and 200+ APIs",
    docsUrl: "https://developers.google.com/api-client-library/javascript",
    githubUrl: "https://github.com/googleapis/google-api-nodejs-client",
    npmPackage: "googleapis",
    language: ["typescript", "javascript"],
    tags: ["google", "api", "sheets", "drive", "calendar", "youtube"],
    bestPracticesPaths: [
      "/api-client-library/javascript/start/start-node",
      "/sheets/api/guides/concepts",
      "/drive/api/guides/about-sdk",
    ],
    urlPatterns: ["/api-client-library/javascript/{slug}"],
  },
  {
    id: "google/vertex-ai-sdk",
    name: "Google Vertex AI",
    aliases: ["vertex-ai", "vertex", "google-vertex"],
    description: "Google Vertex AI platform for ML and generative AI",
    docsUrl: "https://cloud.google.com/vertex-ai/docs",
    language: ["typescript", "javascript", "python"],
    tags: ["ai", "ml", "google", "cloud", "vertex"],
    bestPracticesPaths: [
      "/vertex-ai/docs/start/introduction-unified-platform",
      "/vertex-ai/docs/generative-ai/learn/overview",
      "/vertex-ai/docs/generative-ai/model-garden/explore-models",
      "/vertex-ai/docs/generative-ai/embeddings/get-text-embeddings",
      "/vertex-ai/docs/training/overview",
    ],
    urlPatterns: ["/vertex-ai/docs/{slug}", "/vertex-ai/docs/generative-ai/{slug}"],
  },
  {
    id: "google/maps-js-api",
    name: "Google Maps JavaScript API",
    aliases: ["google-maps", "google-maps-api", "@googlemaps/js-api-loader"],
    description: "Google Maps JavaScript API for interactive maps and location services",
    docsUrl: "https://developers.google.com/maps/documentation/javascript",
    githubUrl: "https://github.com/googlemaps/js-api-loader",
    npmPackage: "@googlemaps/js-api-loader",
    language: ["typescript", "javascript"],
    tags: ["google", "maps", "geolocation", "places"],
    bestPracticesPaths: [
      "/maps/documentation/javascript/overview",
      "/maps/documentation/javascript/markers",
      "/maps/documentation/javascript/geocoding",
      "/maps/documentation/javascript/places",
      "/maps/documentation/javascript/directions",
    ],
    urlPatterns: ["/maps/documentation/javascript/{slug}"],
  },
  {
    id: "google/material-web",
    name: "Material Design",
    aliases: ["material-design", "material-web", "@material/web", "md3"],
    description: "Material Design 3 web components by Google",
    docsUrl: "https://m3.material.io",
    githubUrl: "https://github.com/nicwer/material-web",
    npmPackage: "@material/web",
    language: ["typescript", "javascript"],
    tags: ["ui", "components", "google", "design-system"],
    bestPracticesPaths: [
      "/foundations",
      "/styles",
      "/components",
      "/develop/web",
    ],
    urlPatterns: ["/foundations/{slug}", "/components/{slug}", "/styles/{slug}"],
  },
  {
    id: "flutter/flutter",
    name: "Flutter",
    aliases: ["flutter", "dart-flutter"],
    description: "Google's UI toolkit for building natively compiled applications",
    docsUrl: "https://docs.flutter.dev",
    llmsTxtUrl: "https://docs.flutter.dev/llms.txt",
    githubUrl: "https://github.com/flutter/flutter",
    language: ["dart"],
    tags: ["mobile", "cross-platform", "google", "ui"],
    bestPracticesPaths: [
      "/get-started/install",
      "/cookbook",
      "/ui/widgets",
      "/data-and-backend/state-mgmt",
      "/testing/overview",
      "/deployment",
      "/perf",
    ],
    urlPatterns: ["/docs/{slug}", "/cookbook/{slug}"],
  },
  {
    id: "angular/angular",
    name: "Angular",
    aliases: ["angular", "@angular/core"],
    description: "Google's platform for building web applications",
    docsUrl: "https://angular.dev",
    llmsTxtUrl: "https://angular.dev/llms.txt",
    githubUrl: "https://github.com/angular/angular",
    npmPackage: "@angular/core",
    language: ["typescript"],
    tags: ["framework", "frontend", "google", "spa"],
    bestPracticesPaths: [
      "/overview",
      "/essentials/components",
      "/guide/signals",
      "/guide/di",
      "/guide/routing",
      "/guide/forms",
      "/guide/http",
      "/guide/testing",
    ],
    urlPatterns: ["/guide/{slug}", "/essentials/{slug}"],
  },

  // ─── Anthropic / Claude (expanded) ──────────────────────────────────────────
  {
    id: "anthropics/anthropic-sdk-python",
    name: "Anthropic Python SDK",
    aliases: ["anthropic-python", "anthropic-sdk-python", "claude-python"],
    description: "Official Python SDK for the Anthropic Claude API",
    docsUrl: "https://docs.anthropic.com",
    llmsTxtUrl: "https://platform.claude.com/llms.txt",
    githubUrl: "https://github.com/anthropics/anthropic-sdk-python",
    pypiPackage: "anthropic",
    language: ["python"],
    tags: ["ai", "llm", "sdk", "claude"],
    bestPracticesPaths: [
      "/en/docs/build-with-claude/overview",
      "/en/docs/build-with-claude/tool-use",
      "/en/docs/build-with-claude/prompt-engineering/overview",
      "/en/docs/build-with-claude/streaming",
    ],
    urlPatterns: ["/en/docs/{slug}", "/en/docs/build-with-claude/{slug}"],
  },
  {
    id: "anthropics/anthropic-api",
    name: "Anthropic API",
    aliases: ["claude-api", "anthropic-api", "claude-docs"],
    description: "Complete Anthropic Claude API documentation — messages, tool use, vision, caching, batches",
    docsUrl: "https://docs.anthropic.com",
    llmsTxtUrl: "https://platform.claude.com/llms.txt",
    language: ["typescript", "javascript", "python"],
    tags: ["ai", "llm", "api", "claude"],
    bestPracticesPaths: [
      "/en/docs/welcome",
      "/en/docs/quickstart",
      "/en/docs/build-with-claude/prompt-engineering/overview",
      "/en/docs/build-with-claude/prompt-caching",
      "/en/docs/build-with-claude/tool-use",
      "/en/docs/build-with-claude/vision",
      "/en/docs/build-with-claude/pdf-support",
      "/en/docs/build-with-claude/extended-thinking",
      "/en/docs/build-with-claude/streaming",
      "/en/docs/build-with-claude/message-batches",
      "/en/docs/build-with-claude/computer-use",
      "/en/docs/build-with-claude/citations",
      "/en/docs/build-with-claude/token-counting",
      "/en/docs/build-with-claude/embeddings",
      "/en/docs/about-claude/models",
      "/en/docs/about-claude/models/all-models",
      "/en/docs/about-claude/use-case-guides",
      "/en/api/getting-started",
      "/en/api/messages",
      "/en/api/messages-streaming",
      "/en/api/rate-limits",
      "/en/api/errors",
      "/en/api/versioning",
      "/en/docs/resources/model-deprecations",
      "/en/docs/resources/glossary",
    ],
    urlPatterns: ["/en/docs/{slug}", "/en/docs/build-with-claude/{slug}", "/en/api/{slug}"],
  },

  // ─── OpenAI (expanded) ──────────────────────────────────────────────────────
  {
    id: "openai/openai-python",
    name: "OpenAI Python SDK",
    aliases: ["openai-python", "openai-sdk-python"],
    description: "Official Python SDK for the OpenAI API",
    docsUrl: "https://platform.openai.com/docs",
    githubUrl: "https://github.com/openai/openai-python",
    pypiPackage: "openai",
    language: ["python"],
    tags: ["ai", "llm", "sdk", "openai"],
    bestPracticesPaths: [
      "/docs/guides/text-generation",
      "/docs/guides/function-calling",
      "/docs/guides/structured-outputs",
      "/docs/guides/production-best-practices",
    ],
    urlPatterns: ["/docs/{slug}", "/docs/guides/{slug}"],
  },
  {
    id: "openai/openai-api",
    name: "OpenAI API",
    aliases: ["openai-api", "chatgpt-api", "gpt-api", "openai-docs"],
    description: "Complete OpenAI API documentation — chat completions, assistants, embeddings, images, audio, fine-tuning",
    docsUrl: "https://platform.openai.com/docs",
    language: ["typescript", "javascript", "python"],
    tags: ["ai", "llm", "api", "openai", "gpt"],
    bestPracticesPaths: [
      "/docs/overview",
      "/docs/quickstart",
      "/docs/api-reference/chat",
      "/docs/api-reference/responses",
      "/docs/guides/text-generation",
      "/docs/guides/function-calling",
      "/docs/guides/structured-outputs",
      "/docs/guides/prompt-engineering",
      "/docs/guides/embeddings",
      "/docs/guides/fine-tuning",
      "/docs/guides/images",
      "/docs/guides/speech-to-text",
      "/docs/guides/text-to-speech",
      "/docs/guides/vision",
      "/docs/guides/realtime",
      "/docs/guides/batch",
      "/docs/guides/moderation",
      "/docs/guides/safety-best-practices",
      "/docs/guides/rate-limits",
      "/docs/guides/error-codes",
      "/docs/guides/production-best-practices",
      "/docs/guides/latency-optimization",
    ],
    urlPatterns: ["/docs/{slug}", "/docs/guides/{slug}", "/docs/api-reference/{slug}"],
  },
  {
    id: "openai/openai-agents-python",
    name: "OpenAI Agents SDK",
    aliases: ["openai-agents", "openai-agents-sdk", "openai-swarm"],
    description: "OpenAI Agents SDK for building multi-agent systems with tool use and handoffs",
    docsUrl: "https://openai.github.io/openai-agents-python",
    llmsTxtUrl: "https://openai.github.io/openai-agents-python/llms.txt",
    githubUrl: "https://github.com/openai/openai-agents-python",
    pypiPackage: "openai-agents",
    language: ["python"],
    tags: ["ai", "agent", "sdk", "openai", "multi-agent"],
    bestPracticesPaths: [
      "/quickstart",
      "/agents",
      "/running_agents",
      "/results",
      "/tools",
      "/handoffs",
      "/tracing",
      "/guardrails",
      "/multi_agent",
      "/models",
      "/config",
    ],
    urlPatterns: ["/{slug}"],
  },

  // ─── LangChain / LlamaIndex / AI Frameworks ────────────────────────────────
  {
    id: "langchain-ai/langchainjs",
    name: "LangChain.js",
    aliases: ["langchain", "langchainjs", "langchain-js"],
    description: "Framework for developing applications powered by LLMs — JavaScript/TypeScript",
    docsUrl: "https://js.langchain.com/docs/introduction",
    llmsTxtUrl: "https://js.langchain.com/llms.txt",
    githubUrl: "https://github.com/langchain-ai/langchainjs",
    npmPackage: "langchain",
    language: ["typescript", "javascript"],
    tags: ["ai", "llm", "framework", "rag", "agents"],
    bestPracticesPaths: [
      "/docs/introduction",
      "/docs/concepts",
      "/docs/tutorials/rag",
      "/docs/tutorials/agents",
      "/docs/tutorials/chatbots",
      "/docs/how_to/streaming",
      "/docs/how_to/tool_calling",
      "/docs/how_to/structured_output",
    ],
    urlPatterns: ["/docs/{slug}", "/docs/how_to/{slug}", "/docs/tutorials/{slug}"],
  },
  {
    id: "langchain-ai/langchain",
    name: "LangChain Python",
    aliases: ["langchain-python", "langchain-py"],
    description: "Framework for developing applications powered by LLMs — Python",
    docsUrl: "https://python.langchain.com/docs/introduction",
    llmsTxtUrl: "https://python.langchain.com/llms.txt",
    githubUrl: "https://github.com/langchain-ai/langchain",
    pypiPackage: "langchain",
    language: ["python"],
    tags: ["ai", "llm", "framework", "rag", "agents"],
    bestPracticesPaths: [
      "/docs/concepts/",
      "/docs/how_to/",
      "/docs/tutorials/rag/",
      "/docs/tutorials/agents/",
    ],
    urlPatterns: ["/docs/{slug}", "/docs/how_to/{slug}", "/docs/tutorials/{slug}"],
  },
  {
    id: "langchain-ai/langgraph",
    name: "LangGraph",
    aliases: ["langgraph", "lang-graph"],
    description: "Build stateful multi-agent applications with LLMs as graphs",
    docsUrl: "https://langchain-ai.github.io/langgraph",
    llmsTxtUrl: "https://langchain-ai.github.io/langgraph/llms.txt",
    githubUrl: "https://github.com/langchain-ai/langgraph",
    npmPackage: "@langchain/langgraph",
    pypiPackage: "langgraph",
    language: ["typescript", "javascript", "python"],
    tags: ["ai", "agent", "graph", "stateful", "multi-agent"],
    bestPracticesPaths: [
      "/tutorials/quickstart",
      "/concepts",
      "/how-tos",
    ],
    urlPatterns: ["/tutorials/{slug}", "/concepts/{slug}", "/how-tos/{slug}"],
  },
  {
    id: "run-llama/llama_index",
    name: "LlamaIndex",
    aliases: ["llamaindex", "llama-index", "llama_index"],
    description: "Data framework for LLM applications — connect custom data to LLMs",
    docsUrl: "https://docs.llamaindex.ai/en/stable",
    llmsTxtUrl: "https://docs.llamaindex.ai/llms.txt",
    githubUrl: "https://github.com/run-llama/llama_index",
    pypiPackage: "llama-index",
    language: ["python"],
    tags: ["ai", "llm", "rag", "data", "embeddings"],
    bestPracticesPaths: [
      "/en/stable/getting_started/concepts",
      "/en/stable/module_guides/indexing",
      "/en/stable/module_guides/querying",
      "/en/stable/module_guides/deploying",
    ],
    urlPatterns: ["/en/stable/{slug}", "/en/stable/module_guides/{slug}"],
  },
  {
    id: "joaomdmoura/crewai",
    name: "CrewAI",
    aliases: ["crewai", "crew-ai"],
    description: "Framework for orchestrating role-playing AI agents",
    docsUrl: "https://docs.crewai.com",
    llmsTxtUrl: "https://docs.crewai.com/llms.txt",
    githubUrl: "https://github.com/joaomdmoura/crewAI",
    pypiPackage: "crewai",
    language: ["python"],
    tags: ["ai", "agent", "multi-agent", "orchestration"],
    bestPracticesPaths: [
      "/introduction",
      "/concepts/agents",
      "/concepts/tasks",
      "/concepts/crews",
      "/concepts/tools",
    ],
    urlPatterns: ["/concepts/{slug}", "/how-to/{slug}"],
  },
  {
    id: "microsoft/autogen",
    name: "AutoGen",
    aliases: ["autogen", "auto-gen", "ag2"],
    description: "Microsoft's framework for building multi-agent AI systems",
    docsUrl: "https://microsoft.github.io/autogen",
    githubUrl: "https://github.com/microsoft/autogen",
    pypiPackage: "autogen-agentchat",
    language: ["python"],
    tags: ["ai", "agent", "multi-agent", "microsoft"],
    bestPracticesPaths: [
      "/docs/Getting-Started",
      "/docs/Use-Cases/agent_chat",
      "/docs/FAQ",
    ],
    urlPatterns: ["/docs/{slug}", "/docs/Use-Cases/{slug}"],
  },

  // ─── AI Model Providers ─────────────────────────────────────────────────────
  {
    id: "mistralai/client-js",
    name: "Mistral AI",
    aliases: ["mistral", "mistral-ai", "@mistralai/mistralai"],
    description: "Official Mistral AI client for JavaScript and TypeScript",
    docsUrl: "https://docs.mistral.ai",
    llmsTxtUrl: "https://docs.mistral.ai/llms.txt",
    githubUrl: "https://github.com/mistralai/client-js",
    npmPackage: "@mistralai/mistralai",
    language: ["typescript", "javascript"],
    tags: ["ai", "llm", "sdk", "mistral"],
    bestPracticesPaths: [
      "/getting-started/quickstart",
      "/capabilities/completion",
      "/capabilities/function_calling",
      "/capabilities/embeddings",
      "/capabilities/vision",
      "/capabilities/agents",
      "/capabilities/finetuning",
    ],
    urlPatterns: ["/capabilities/{slug}", "/getting-started/{slug}"],
  },
  {
    id: "cohere-ai/cohere-typescript",
    name: "Cohere",
    aliases: ["cohere", "cohere-ai"],
    description: "Cohere API client — text generation, embeddings, reranking, and RAG",
    docsUrl: "https://docs.cohere.com",
    llmsTxtUrl: "https://docs.cohere.com/llms.txt",
    githubUrl: "https://github.com/cohere-ai/cohere-typescript",
    npmPackage: "cohere-ai",
    language: ["typescript", "javascript"],
    tags: ["ai", "llm", "embeddings", "reranking", "rag"],
    bestPracticesPaths: [
      "/docs/the-cohere-platform",
      "/docs/chat-api",
      "/docs/embed-api",
      "/docs/rerank-api",
      "/docs/rag",
    ],
    urlPatterns: ["/docs/{slug}"],
  },
  {
    id: "groq/groq-typescript",
    name: "Groq",
    aliases: ["groq", "groq-sdk", "groq-ai"],
    description: "Groq API client — ultra-fast LLM inference",
    docsUrl: "https://console.groq.com/docs",
    llmsTxtUrl: "https://console.groq.com/llms.txt",
    githubUrl: "https://github.com/groq/groq-typescript",
    npmPackage: "groq-sdk",
    language: ["typescript", "javascript"],
    tags: ["ai", "llm", "sdk", "inference", "fast"],
    bestPracticesPaths: [
      "/docs/quickstart",
      "/docs/text-chat",
      "/docs/tool-use",
    ],
    urlPatterns: ["/docs/{slug}"],
  },
  {
    id: "replicate/replicate-javascript",
    name: "Replicate",
    aliases: ["replicate"],
    description: "Run and fine-tune open-source AI models via API",
    docsUrl: "https://replicate.com/docs",
    llmsTxtUrl: "https://replicate.com/llms.txt",
    githubUrl: "https://github.com/replicate/replicate-javascript",
    npmPackage: "replicate",
    language: ["typescript", "javascript"],
    tags: ["ai", "ml", "inference", "open-source"],
    bestPracticesPaths: [
      "/docs/get-started/nodejs",
      "/docs/reference/http",
      "/docs/guides/fine-tune-a-model",
    ],
    urlPatterns: ["/docs/{slug}", "/docs/guides/{slug}", "/docs/reference/{slug}"],
  },
  {
    id: "together-ai/together-typescript",
    name: "Together AI",
    aliases: ["together", "together-ai", "togetherai"],
    description: "Together AI inference platform — run open-source models at scale",
    docsUrl: "https://docs.together.ai",
    llmsTxtUrl: "https://docs.together.ai/llms.txt",
    githubUrl: "https://github.com/togethercomputer/together-typescript",
    npmPackage: "together-ai",
    language: ["typescript", "javascript"],
    tags: ["ai", "llm", "inference", "open-source"],
    bestPracticesPaths: [
      "/docs/quickstart",
      "/docs/inference-models",
      "/docs/fine-tuning",
    ],
    urlPatterns: ["/docs/{slug}"],
  },
  {
    id: "fireworks-ai/fireworks-js",
    name: "Fireworks AI",
    aliases: ["fireworks", "fireworks-ai"],
    description: "Fireworks AI inference platform for generative AI models",
    docsUrl: "https://docs.fireworks.ai",
    llmsTxtUrl: "https://docs.fireworks.ai/llms.txt",
    npmPackage: "@fireworks-ai/fireworks-js",
    language: ["typescript", "javascript"],
    tags: ["ai", "llm", "inference"],
    bestPracticesPaths: [
      "/guides/querying-text-models",
      "/guides/querying-vision-language-models",
      "/guides/function-calling",
    ],
    urlPatterns: ["/guides/{slug}", "/api-reference/{slug}"],
  },

  // ─── Vector Databases ───────────────────────────────────────────────────────
  {
    id: "pinecone-io/pinecone-ts-client",
    name: "Pinecone",
    aliases: ["pinecone", "@pinecone-database/pinecone"],
    description: "Pinecone vector database client for TypeScript",
    docsUrl: "https://docs.pinecone.io",
    llmsTxtUrl: "https://docs.pinecone.io/llms.txt",
    githubUrl: "https://github.com/pinecone-io/pinecone-ts-client",
    npmPackage: "@pinecone-database/pinecone",
    language: ["typescript", "javascript"],
    tags: ["database", "vector", "embeddings", "ai"],
    bestPracticesPaths: [
      "/guides/get-started/quickstart",
      "/guides/data/upsert-data",
      "/guides/data/query-data",
      "/guides/indexes/create-index",
    ],
    urlPatterns: ["/guides/{slug}", "/guides/data/{slug}", "/guides/indexes/{slug}"],
  },
  {
    id: "chroma-core/chromadb",
    name: "Chroma",
    aliases: ["chroma", "chromadb"],
    description: "Open-source embedding database for AI applications",
    docsUrl: "https://docs.trychroma.com",
    llmsTxtUrl: "https://docs.trychroma.com/llms.txt",
    githubUrl: "https://github.com/chroma-core/chroma",
    npmPackage: "chromadb",
    pypiPackage: "chromadb",
    language: ["typescript", "javascript", "python"],
    tags: ["database", "vector", "embeddings", "ai", "open-source"],
    bestPracticesPaths: [
      "/docs/overview/getting-started",
      "/docs/collections/create-get-delete",
      "/docs/collections/add-data",
      "/docs/collections/query-data",
    ],
    urlPatterns: ["/docs/{slug}", "/docs/collections/{slug}"],
  },
  {
    id: "weaviate/typescript-client",
    name: "Weaviate",
    aliases: ["weaviate"],
    description: "Open-source vector database for AI-native applications",
    docsUrl: "https://weaviate.io/developers/weaviate",
    llmsTxtUrl: "https://weaviate.io/llms.txt",
    githubUrl: "https://github.com/weaviate/typescript-client",
    npmPackage: "weaviate-client",
    language: ["typescript", "javascript"],
    tags: ["database", "vector", "embeddings", "ai"],
    bestPracticesPaths: [
      "/developers/weaviate/starter-guides",
      "/developers/weaviate/manage-data",
      "/developers/weaviate/search",
      "/developers/weaviate/configuration",
    ],
    urlPatterns: ["/developers/weaviate/{slug}"],
  },
  {
    id: "qdrant/js-client-rest",
    name: "Qdrant",
    aliases: ["qdrant"],
    description: "High-performance vector search engine",
    docsUrl: "https://qdrant.tech/documentation",
    llmsTxtUrl: "https://qdrant.tech/llms.txt",
    githubUrl: "https://github.com/qdrant/qdrant-js",
    npmPackage: "@qdrant/js-client-rest",
    language: ["typescript", "javascript"],
    tags: ["database", "vector", "search", "ai"],
    bestPracticesPaths: [
      "/documentation/guides/",
      "/documentation/concepts/",
      "/documentation/quick-start/",
    ],
    urlPatterns: ["/documentation/{slug}", "/documentation/guides/{slug}"],
  },

  // ─── AI Audio / Voice ───────────────────────────────────────────────────────
  {
    id: "elevenlabs/elevenlabs-js",
    name: "ElevenLabs",
    aliases: ["elevenlabs", "eleven-labs"],
    description: "ElevenLabs API for text-to-speech, voice cloning, and audio AI",
    docsUrl: "https://elevenlabs.io/docs",
    githubUrl: "https://github.com/elevenlabs/elevenlabs-js",
    npmPackage: "elevenlabs",
    language: ["typescript", "javascript"],
    tags: ["ai", "audio", "tts", "voice"],
    bestPracticesPaths: [
      "/docs/quickstart",
      "/docs/api-reference/text-to-speech",
      "/docs/guides/voice-cloning",
    ],
    urlPatterns: ["/docs/{slug}", "/docs/api-reference/{slug}", "/docs/guides/{slug}"],
  },
  {
    id: "deepgram/deepgram-js-sdk",
    name: "Deepgram",
    aliases: ["deepgram"],
    description: "Deepgram API for speech-to-text, text-to-speech, and audio intelligence",
    docsUrl: "https://developers.deepgram.com/docs",
    llmsTxtUrl: "https://developers.deepgram.com/llms.txt",
    githubUrl: "https://github.com/deepgram/deepgram-js-sdk",
    npmPackage: "@deepgram/sdk",
    language: ["typescript", "javascript"],
    tags: ["ai", "audio", "stt", "tts", "speech"],
    bestPracticesPaths: [
      "/docs/getting-started",
      "/docs/speech-to-text",
      "/docs/text-to-speech",
    ],
    urlPatterns: ["/docs/{slug}", "/reference/{slug}"],
  },
  {
    id: "AssemblyAI/assemblyai-node-sdk",
    name: "AssemblyAI",
    aliases: ["assemblyai", "assembly-ai"],
    description: "AssemblyAI API for speech-to-text, speaker diarization, and audio intelligence",
    docsUrl: "https://www.assemblyai.com/docs",
    githubUrl: "https://github.com/AssemblyAI/assemblyai-node-sdk",
    npmPackage: "assemblyai",
    language: ["typescript", "javascript"],
    tags: ["ai", "audio", "stt", "transcription"],
    bestPracticesPaths: [
      "/docs/getting-started",
      "/docs/speech-to-text/pre-recorded",
      "/docs/speech-to-text/streaming",
    ],
    urlPatterns: ["/docs/{slug}", "/docs/speech-to-text/{slug}"],
  },

  // ─── AI Image / Video ──────────────────────────────────────────────────────
  {
    id: "stability-ai/stability-sdk",
    name: "Stability AI",
    aliases: ["stability", "stability-ai", "stable-diffusion-api"],
    description: "Stability AI API for image generation, editing, and video",
    docsUrl: "https://platform.stability.ai/docs",
    language: ["typescript", "javascript", "python"],
    tags: ["ai", "image", "generation", "stable-diffusion"],
    bestPracticesPaths: [
      "/docs/getting-started",
      "/docs/api-reference",
    ],
    urlPatterns: ["/docs/{slug}"],
  },
  {
    id: "fal-ai/fal-js",
    name: "fal.ai",
    aliases: ["fal", "fal-ai"],
    description: "Run and deploy AI models on fal.ai — image, video, and audio generation",
    docsUrl: "https://fal.ai/docs",
    llmsTxtUrl: "https://fal.ai/llms.txt",
    githubUrl: "https://github.com/fal-ai/fal-js",
    npmPackage: "@fal-ai/client",
    language: ["typescript", "javascript"],
    tags: ["ai", "inference", "image", "video"],
    bestPracticesPaths: [
      "/docs/quickstart",
      "/docs/model-endpoints",
    ],
    urlPatterns: ["/docs/{slug}"],
  },

  // ─── Hugging Face ───────────────────────────────────────────────────────────
  {
    id: "huggingface/huggingface.js",
    name: "Hugging Face JS",
    aliases: ["huggingface", "hf", "@huggingface/inference", "huggingface-js"],
    description: "Hugging Face client libraries for JavaScript — inference, hub, and transformers.js",
    docsUrl: "https://huggingface.co/docs/huggingface.js",
    githubUrl: "https://github.com/huggingface/huggingface.js",
    npmPackage: "@huggingface/inference",
    language: ["typescript", "javascript"],
    tags: ["ai", "ml", "inference", "hub", "models"],
    bestPracticesPaths: [
      "/docs/huggingface.js/inference/overview",
      "/docs/huggingface.js/hub/overview",
    ],
    urlPatterns: ["/docs/huggingface.js/{slug}"],
  },
  {
    id: "huggingface/transformers.js",
    name: "Transformers.js",
    aliases: ["transformers-js", "transformersjs", "@huggingface/transformers"],
    description: "Run Hugging Face Transformers models directly in the browser",
    docsUrl: "https://huggingface.co/docs/transformers.js",
    githubUrl: "https://github.com/huggingface/transformers.js",
    npmPackage: "@huggingface/transformers",
    language: ["typescript", "javascript"],
    tags: ["ai", "ml", "browser", "inference", "wasm"],
    bestPracticesPaths: [
      "/docs/transformers.js/index",
      "/docs/transformers.js/guides/node-esm",
    ],
    urlPatterns: ["/docs/transformers.js/{slug}"],
  },
  {
    id: "huggingface/transformers",
    name: "Hugging Face Transformers",
    aliases: ["transformers", "hf-transformers"],
    description: "State-of-the-art ML models for PyTorch, TensorFlow, and JAX",
    docsUrl: "https://huggingface.co/docs/transformers",
    githubUrl: "https://github.com/huggingface/transformers",
    pypiPackage: "transformers",
    language: ["python"],
    tags: ["ai", "ml", "nlp", "vision", "models"],
    bestPracticesPaths: [
      "/docs/transformers/main/en/quicktour",
      "/docs/transformers/main/en/performance",
      "/docs/transformers/main/en/training",
    ],
    urlPatterns: ["/docs/transformers/main/en/{slug}"],
  },

  // ─── ML / Deep Learning ─────────────────────────────────────────────────────
  {
    id: "pytorch/pytorch",
    name: "PyTorch",
    aliases: ["pytorch", "torch"],
    description: "Open-source machine learning framework for Python",
    docsUrl: "https://pytorch.org/docs/stable",
    githubUrl: "https://github.com/pytorch/pytorch",
    pypiPackage: "torch",
    language: ["python"],
    tags: ["ml", "deep-learning", "neural-networks", "gpu"],
    bestPracticesPaths: [
      "/docs/stable/notes/cuda",
      "/tutorials/beginner/basics/intro",
      "/docs/stable/notes/multiprocessing",
    ],
    urlPatterns: ["/docs/stable/{slug}", "/tutorials/{slug}"],
  },
  {
    id: "tensorflow/tensorflow",
    name: "TensorFlow",
    aliases: ["tensorflow", "tf"],
    description: "Open-source platform for machine learning",
    docsUrl: "https://www.tensorflow.org/api_docs",
    githubUrl: "https://github.com/tensorflow/tensorflow",
    pypiPackage: "tensorflow",
    language: ["python"],
    tags: ["ml", "deep-learning", "neural-networks", "google"],
    bestPracticesPaths: [
      "/guide",
      "/tutorials",
      "/guide/keras",
      "/guide/gpu",
    ],
    urlPatterns: ["/guide/{slug}", "/tutorials/{slug}", "/api_docs/python/{slug}"],
  },

  // ─── Payments / Email / Services ────────────────────────────────────────────
  {
    id: "stripe/stripe-node",
    name: "Stripe",
    aliases: ["stripe", "stripe-js"],
    description: "Stripe API client for payments, subscriptions, and billing",
    docsUrl: "https://docs.stripe.com",
    llmsTxtUrl: "https://docs.stripe.com/llms.txt",
    githubUrl: "https://github.com/stripe/stripe-node",
    npmPackage: "stripe",
    language: ["typescript", "javascript"],
    tags: ["payments", "billing", "subscriptions", "fintech"],
    bestPracticesPaths: [
      "/payments/quickstart",
      "/payments/payment-intents",
      "/billing/subscriptions/overview",
      "/webhooks",
      "/security",
    ],
    urlPatterns: ["/payments/{slug}", "/billing/{slug}", "/webhooks/{slug}"],
  },
  {
    id: "resend/resend-node",
    name: "Resend",
    aliases: ["resend"],
    description: "Email API for developers — send transactional and marketing emails",
    docsUrl: "https://resend.com/docs",
    llmsTxtUrl: "https://resend.com/llms.txt",
    githubUrl: "https://github.com/resend/resend-node",
    npmPackage: "resend",
    language: ["typescript", "javascript"],
    tags: ["email", "api", "transactional"],
    bestPracticesPaths: [
      "/docs/introduction",
      "/docs/send-with-react",
      "/docs/idempotency",
    ],
    urlPatterns: ["/docs/{slug}"],
  },
  {
    id: "upstash/redis",
    name: "Upstash Redis",
    aliases: ["upstash", "upstash-redis", "@upstash/redis"],
    description: "Serverless Redis and Kafka for edge and serverless applications",
    docsUrl: "https://upstash.com/docs/redis/overall/getstarted",
    githubUrl: "https://github.com/upstash/redis-js",
    npmPackage: "@upstash/redis",
    language: ["typescript", "javascript"],
    tags: ["database", "redis", "serverless", "edge", "cache"],
    bestPracticesPaths: [
      "/docs/redis/overall/getstarted",
      "/docs/redis/sdks/ts/overview",
      "/docs/qstash/overview",
    ],
    urlPatterns: ["/docs/redis/{slug}", "/docs/qstash/{slug}"],
  },

  // ─── Monitoring / Observability ─────────────────────────────────────────────
  {
    id: "getsentry/sentry-javascript",
    name: "Sentry",
    aliases: ["sentry", "@sentry/nextjs", "@sentry/node"],
    description: "Application monitoring and error tracking for every platform",
    docsUrl: "https://docs.sentry.io/platforms/javascript",
    githubUrl: "https://github.com/getsentry/sentry-javascript",
    npmPackage: "@sentry/node",
    language: ["typescript", "javascript"],
    tags: ["monitoring", "errors", "performance", "tracing"],
    bestPracticesPaths: [
      "/platforms/javascript/",
      "/platforms/javascript/performance/",
      "/platforms/javascript/session-replay/",
      "/platforms/javascript/guides/nextjs/",
    ],
    urlPatterns: ["/platforms/javascript/{slug}", "/platforms/javascript/guides/{slug}"],
  },
  {
    id: "PostHog/posthog-js",
    name: "PostHog",
    aliases: ["posthog"],
    description: "Open-source product analytics, feature flags, session replays, and A/B testing",
    docsUrl: "https://posthog.com/docs",
    llmsTxtUrl: "https://posthog.com/llms.txt",
    githubUrl: "https://github.com/PostHog/posthog-js",
    npmPackage: "posthog-js",
    language: ["typescript", "javascript"],
    tags: ["analytics", "feature-flags", "product"],
    bestPracticesPaths: [
      "/docs/getting-started/install",
      "/docs/product-analytics",
      "/docs/feature-flags",
      "/docs/session-replay",
    ],
    urlPatterns: ["/docs/{slug}"],
  },

  // ─── Workflow / Automation ──────────────────────────────────────────────────
  {
    id: "n8n-io/n8n",
    name: "n8n",
    aliases: ["n8n"],
    description: "Workflow automation platform with 400+ integrations",
    docsUrl: "https://docs.n8n.io",
    llmsTxtUrl: "https://docs.n8n.io/llms.txt",
    githubUrl: "https://github.com/n8n-io/n8n",
    npmPackage: "n8n",
    language: ["typescript"],
    tags: ["automation", "workflow", "integration"],
    bestPracticesPaths: [
      "/workflows/",
      "/code/",
      "/integrations/",
      "/hosting/",
    ],
    urlPatterns: ["/workflows/{slug}", "/code/{slug}", "/integrations/{slug}"],
  },
  {
    id: "triggerdotdev/trigger.dev",
    name: "Trigger.dev",
    aliases: ["trigger", "trigger.dev", "triggerdev"],
    description: "Background jobs and workflows for TypeScript",
    docsUrl: "https://trigger.dev/docs",
    llmsTxtUrl: "https://trigger.dev/llms.txt",
    githubUrl: "https://github.com/triggerdotdev/trigger.dev",
    npmPackage: "@trigger.dev/sdk",
    language: ["typescript"],
    tags: ["jobs", "background", "workflow", "serverless"],
    bestPracticesPaths: [
      "/docs/quick-start",
      "/docs/guides",
      "/docs/examples",
    ],
    urlPatterns: ["/docs/{slug}", "/docs/guides/{slug}"],
  },

  // ─── Auth (additional) ──────────────────────────────────────────────────────
  {
    id: "better-auth/better-auth",
    name: "Better Auth",
    aliases: ["better-auth", "betterauth"],
    description: "Framework-agnostic authentication and authorization library for TypeScript",
    docsUrl: "https://www.better-auth.com/docs",
    llmsTxtUrl: "https://www.better-auth.com/llms.txt",
    githubUrl: "https://github.com/better-auth/better-auth",
    npmPackage: "better-auth",
    language: ["typescript"],
    tags: ["auth", "oauth", "sessions", "2fa"],
    bestPracticesPaths: [
      "/docs/installation",
      "/docs/authentication/email-password",
      "/docs/authentication/social-sign-on",
      "/docs/plugins",
    ],
    urlPatterns: ["/docs/{slug}", "/docs/authentication/{slug}", "/docs/plugins/{slug}"],
  },
  {
    id: "lucia-auth/lucia",
    name: "Lucia Auth",
    aliases: ["lucia", "lucia-auth"],
    description: "Simple and flexible authentication library for TypeScript",
    docsUrl: "https://lucia-auth.com",
    githubUrl: "https://github.com/lucia-auth/lucia",
    npmPackage: "lucia",
    language: ["typescript"],
    tags: ["auth", "sessions"],
    bestPracticesPaths: [
      "/tutorials/",
      "/guides/validate-session-cookies/",
    ],
    urlPatterns: ["/tutorials/{slug}", "/guides/{slug}"],
  },
];

/** Look up a registry entry by its exact id (e.g. "vercel/next.js"). */
export function lookupById(id: string): LibraryEntry | undefined {
  return LIBRARY_REGISTRY.find((e) => e.id === id);
}

/** Look up a registry entry by name or any of its aliases (case-insensitive). */
export function lookupByAlias(query: string): LibraryEntry | undefined {
  const q = query.toLowerCase().trim();
  return LIBRARY_REGISTRY.find(
    (e) =>
      e.name.toLowerCase() === q ||
      e.id.toLowerCase() === q ||
      (e.aliases ?? []).some((a) => a.toLowerCase() === q) ||
      (e.npmPackage !== undefined && e.npmPackage.toLowerCase() === q),
  );
}

/** Return up to `limit` entries whose name/aliases/tags contain the query string. */
export function fuzzySearch(query: string, limit = 10): LibraryEntry[] {
  const q = query.toLowerCase().trim();
  const scored: Array<{ entry: LibraryEntry; score: number }> = [];

  for (const entry of LIBRARY_REGISTRY) {
    let score = 0;
    const name = entry.name.toLowerCase();
    const id = entry.id.toLowerCase();
    const aliases = (entry.aliases ?? []).map((a) => a.toLowerCase());
    const tags = (entry.tags ?? []).map((t) => t.toLowerCase());
    const desc = (entry.description ?? "").toLowerCase();

    if (name === q || id === q || aliases.includes(q)) score += 100;
    else if (name.startsWith(q) || aliases.some((a) => a.startsWith(q))) score += 50;
    else if (name.includes(q) || id.includes(q) || aliases.some((a) => a.includes(q))) score += 25;
    else if (tags.some((t) => t.includes(q)) || desc.includes(q)) score += 10;

    if (score > 0) scored.push({ entry, score });
  }

  return scored
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map((s) => s.entry);
}
